### ISSUE TITLE
not working for Ebsco APi records

### ISSUE THREAD

**Issue by dlingley** [gabriele-h/PrimoNUIShow#1]
Thanks for sharing!

Currently not working for Ebsco api results... The old showpnx did work with ebsco records though.

Thanks,
Dean

**Comment by dlingley** [comment]
I think the problem is related to the fact the ebsco api records all have third node prefix, but their context would not equal PC... not sure what context should be though or how to differentiate the Ebsco from PCI just based upon initial prefix:
https://www.screencast.com/t/rLcB2Fb8NxR

Example broken link from our primo:
https://purdue-primo-prod.hosted.exlibrisgroup.com/primo-explore/fulldisplay?vid=PURDUE&docid=TN_crh_112319395&context=PC&showPnx=true

**Comment by gabriele-h** [comment]
Thank you for pointing this issue out! And even more so for the screencast and example!

Yes, the TN-prefix is not exclusively used for Primo Central records. I will need to have a look whether there is an easy way to distinguish them from other third node records.

Gabriele

**Comment by gabriele-h** [comment]
I opened a new branch for this issue:
https://github.com/gabriele-h/PrimoNUIShow/blob/urlbuild/bookmarklet.js

In this version the bookmarklet will use the URL provided for accessing the full view when clicking on the media icon (I might change that to the item title link, not sure whether there might be institutions who link somewhere else from the icon than from the title). Before links where built from scratch with parameters from "location".

If you want and find the time, please do some testing! Ebsco "Show Pnx"-links should be working in this version. I have not yet merged this branch, because I want to do some more testing first.

Gabriele
